spring:
  application:
    name: warehouse-cdnsg

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # ĐƯA BLOCK MAIL VÀO ĐÂY, THỤT LỀ NGANG VỚI datasource, jpa...
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_AUTH:true}
          starttls:
            required: true
            enable: ${SPRING_MAIL_STARTTLS_ENABLE:true}
          ssl.trust: ${SPRING_MAIL_HOST:smtp.gmail.com}
  
server:
  port: 8080

app:
  cors:
    origin: ${APP_CORS_ORIGIN:http://localhost:5173}
  extinguisher:
    warning-days: 15
  secret-key: ${APP_SECRET_KEY}
  admin:
    email: ${APP_ADMIN_EMAIL:admin@warehouse-cdnsg.local}
    username: ${APP_ADMIN_USERNAME:admin}
    password: ${APP_ADMIN_PASSWORD:admin123}
    full-name: ${APP_ADMIN_FULLNAME:System Administrator}
    school-id: ${APP_ADMIN_SCHOOL_ID:ADMIN}
  expire: ${APP_EXPIRE_SECONDS:10}

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}

springdoc:
  swagger-ui:
    with-credentials: true