spring:
  application:
    name: warehouse-cdnsg

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        10MB
  
server:
  port: 8080

app:
  cors:
    origin: ${APP_CORS_ORIGIN:http://localhost:5173}

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_KEY}
  api_secret: ${CLOUDINARY_SECRET}